"""add trace_id to messages

Revision ID: 52cf2fe53da2
Revises: 17a39782f6c2
Create Date: 2026-07-16 12:50:14.613478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cf2fe53da2'
down_revision: Union[str, Sequence[str], None] = '17a39782f6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('trace_id', sa.String(length=64), nullable=True))
    op.create_index('ix_messages_trace_id', 'messages', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_trace_id', table_name='messages')
    op.drop_column('messages', 'trace_id')
    # ### end Alembic commands ###
