"""add docgen tables

Revision ID: ba6ef3d81253
Revises: d13f9d6b4f9a
Create Date: 2026-09-03 00:21:33.994454

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba6ef3d81253"
down_revision: str | Sequence[str] | None = "d13f9d6b4f9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docgen_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_type", sa.String(length=32), nullable=False),
        sa.Column("source_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("document_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_docgen_sessions_expires_at", "docgen_sessions", ["expires_at"], unique=False
    )
    op.create_index("ix_docgen_sessions_user_id", "docgen_sessions", ["user_id"], unique=False)
    op.create_table(
        "docgen_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("article_number", sa.Integer(), nullable=False),
        sa.Column("ordinal_words", sa.String(length=64), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("patched_text", sa.Text(), nullable=False),
        sa.Column("patch_ops", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("selected", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("new_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["docgen_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_docgen_articles_session_id_article_number",
        "docgen_articles",
        ["session_id", "article_number"],
        unique=False,
    )
    op.create_table(
        "docgen_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(["session_id"], ["docgen_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "docgen_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=128), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("page_classification", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["docgen_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_docgen_uploads_session_id", "docgen_uploads", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_docgen_uploads_session_id", table_name="docgen_uploads")
    op.drop_table("docgen_uploads")
    op.drop_table("docgen_fields")
    op.drop_index("ix_docgen_articles_session_id_article_number", table_name="docgen_articles")
    op.drop_table("docgen_articles")
    op.drop_index("ix_docgen_sessions_user_id", table_name="docgen_sessions")
    op.drop_index("ix_docgen_sessions_expires_at", table_name="docgen_sessions")
    op.drop_table("docgen_sessions")
    # ### end Alembic commands ###
