"""Build chunks_law72.json: the consolidated investment law, amendments merged.

Pipeline
--------
    extract  ->  correct  ->  patch 32/33  ->  parse articles
             ->  merge amendments  ->  emit chunks + audit

The output matches the schema `arabic_ingest/chunker.py` produces for laws
131 and 174, with two additions:

    metadata.article_suffix   "مكرر" for articles 11 مكررًا and 91 مكررًا,
                              None otherwise. Keeps article_number an int so
                              exact lookup and the citation guard keep working,
                              while still distinguishing م.11 from م.11 مكررًا.
    metadata.amendments       structured record of every amending law that
                              touched the article, so the corpus can be queried
                              by amendment as well as read.

The Arabic amendment notes are woven into body_faithful, text_for_display and
text_for_embedding alike, so the assistant can quote the amendment history and
retrieve on it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SP = Path(__file__).parent
sys.path.insert(0, r"E:\DL projects\Legal Assistant\arabic_ingest")

from arabic_text import normalize_for_embedding  # noqa: E402
from law72_amendment_map import build as build_amendments  # noqa: E402
from law72_amendments import apply_amendments  # noqa: E402
from law72_corrections import (  # noqa: E402
    apply_corrections,
    apply_patches,  # noqa: E402
    find_substantive_defects,
)
from law72_extract import BUILD_DIR, DATA_DIR, extract_pages, prepare  # noqa: E402
from law72_structure import parse, to_arabic_digits  # noqa: E402

LAW_NAME = "قانون الاستثمار"
LAW_NUMBER, LAW_YEAR = 72, 2017
SOURCE_FILE = "قانون الاستثمار رقم 72 لسنة 2017.pdf"
JURISDICTION = "مصر"
CHARS_PER_TOKEN = 1.8

ISSUANCE_ORDINALS = {
    1: "المادة الأولى", 2: "المادة الثانية", 3: "المادة الثالثة",
    4: "المادة الرابعة", 5: "المادة الخامسة", 6: "المادة السادسة",
    7: "المادة السابعة", 8: "المادة الثامنة", 9: "المادة التاسعة",
    10: "المادة العاشرة",
}
INT_TO_ORDINAL = {
    1: "الأول", 2: "الثاني", 3: "الثالث", 4: "الرابع", 5: "الخامس",
    6: "السادس", 7: "السابع", 8: "الثامن", 9: "التاسع", 10: "العاشر",
}


def article_label(number: int, suffix: str | None) -> str:
    """"مادة (١١)" / "مادة (١١ مكررًا)"."""
    n = to_arabic_digits(number)
    return f"مادة ({n} مكررًا)" if suffix else f"مادة ({n})"


def build_header(art, suffix: str | None) -> str:
    lines = [f"{LAW_NAME} رقم ({to_arabic_digits(LAW_NUMBER)}) "
             f"لسنة ({to_arabic_digits(LAW_YEAR)})"]
    if art.kind == "issuance":
        lines.append("من مواد الإصدار")
        lines.append(ISSUANCE_ORDINALS[art.number])
        return "\n".join(lines)
    if art.book_number:
        lines.append(f"الباب {INT_TO_ORDINAL[art.book_number]}: {art.book_title}")
    if art.chapter_number:
        lines.append(f"الفصل {INT_TO_ORDINAL[art.chapter_number]}: {art.chapter_title}")
    if art.section_title:
        lines.append(art.section_title)
    lines.append(article_label(art.number, suffix))
    return "\n".join(lines)


def build_citation(art, suffix: str | None) -> str:
    law = f"من {LAW_NAME} رقم {to_arabic_digits(LAW_NUMBER)} لسنة {to_arabic_digits(LAW_YEAR)}"
    if art.kind == "issuance":
        return (f"{ISSUANCE_ORDINALS[art.number]} من مواد إصدار {LAW_NAME} "
                f"رقم {to_arabic_digits(LAW_NUMBER)} لسنة {to_arabic_digits(LAW_YEAR)}")
    n = to_arabic_digits(art.number)
    base = f"المادة ({n} مكررًا) {law}" if suffix else f"المادة ({n}) {law}"
    qualifier = art.chapter_title or art.book_title
    return f"{base} ({qualifier})" if qualifier else base


def chunk_id(art, suffix: str | None) -> str:
    base = f"{LAW_NUMBER}-{LAW_YEAR}"
    if art.kind == "issuance":
        return f"{base}-issuance-{art.number}"
    return f"{base}-art-{art.number}-mukarrar" if suffix else f"{base}-art-{art.number}"


class Bis:
    """A مكرر article carries no own structure -- it inherits its neighbour's."""

    def __init__(self, number, suffix, sibling):
        self.kind = "substantive"
        self.number = number
        self.suffix = suffix
        self.book_number, self.book_title = sibling.book_number, sibling.book_title
        self.chapter_number = sibling.chapter_number
        self.chapter_title = sibling.chapter_title
        self.section_title = sibling.section_title
        self.page_start = self.page_end = 0


AUDIT_PREAMBLE = """# Law 72/2017 ingest -- record of every intervention

Generated by `build_law72.py`. Read this before ingesting: it lists everything
this pipeline changed relative to the raw PDFs, so each edit can be checked
against the source pages.

**Why there is anything to review at all.** The two amending laws (141/2019,
160/2023) are clean official Gazette texts. The base 72/2017 PDF is not -- it
is an unofficial retyped copy carrying roughly a hundred word-level defects
(transposed and dropped letters, words run together) plus a structural gap
where article 33's header is missing entirely. Sourcing a Gazette-quality
72/2017 PDF and re-running this build would make most of section 1 disappear.

**What was NOT changed.** Hamza-seat inconsistency (الأستثمار / الإستثمار /
الاستثمار) is left as the source wrote it -- the retrieval copy folds hamza
anyway, so it costs nothing, and normalising it would be a style edit rather
than a defect repair. Transliterated trade terms (سيف = CIF, فوب = FOB) are
correct legal usage and are left alone. Section 2 lists the defects that could
not be repaired without the official text; those are reported, never guessed.

"""


def main() -> int:
    audit: list[str] = [AUDIT_PREAMBLE]

    # 1. extract ------------------------------------------------------------
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    paths = prepare(DATA_DIR, BUILD_DIR / "pdf")
    for key, pdf in paths.items():
        pages = extract_pages(pdf)
        text = "\n".join(f"===== PAGE {i} =====\n{p}" for i, p in enumerate(pages, 1))
        (BUILD_DIR / f"{key}_fixed.txt").write_text(text, encoding="utf-8")
    raw = (BUILD_DIR / "base72_fixed.txt").read_text(encoding="utf-8")

    # 2. reviewed typo corrections -----------------------------------------
    corrected, fix_log = apply_corrections(raw)
    audit.append(f"## 1. Source typo corrections ({len(fix_log)} distinct, "
                 f"{sum(n for _, _, n in fix_log)} occurrences)\n")
    audit.append("Each entry is a word whose intended reading is unambiguous from the\n"
                 "surrounding legal sentence. Table: `law72_corrections.py`.\n")
    for bad, good, n in sorted(fix_log):
        audit.append(f"  {bad}  ->  {good}   (x{n})")

    defects = find_substantive_defects(raw)
    audit.append(f"\n## 2. Substantive defects left in place ({len(defects)})\n")
    audit.append("The source states something legally wrong here. Repairing it would mean\n"
                 "writing law, so it is surfaced instead of guessed.\n")
    for marker, note in defects:
        audit.append(f"  {marker}\n      {note}")

    # 3. structural patch ---------------------------------------------------
    patched, patch_log = apply_patches(corrected)
    audit.append(f"\n## 3. Structural patches ({len(patch_log)})\n")
    audit.append("Replacement text supplied by the project owner and diffed sentence by\n"
                 "sentence against the extraction before being applied.\n")
    audit.extend(f"  {why}" for why in patch_log)
    (BUILD_DIR / "base72_corrected.txt").write_text(patched, encoding="utf-8")

    # 4. parse --------------------------------------------------------------
    articles = parse(patched)
    subs = [a for a in articles if a.kind == "substantive"]
    numbers = [a.number for a in subs]
    missing = [n for n in range(1, 95) if n not in numbers]
    if missing or len(set(numbers)) != len(numbers):
        print(f"ERROR: article numbering broken. missing={missing}", file=sys.stderr)
        return 1

    # 5. merge amendments ---------------------------------------------------
    amendments = build_amendments()
    by_target: dict[tuple[int, str | None], list] = {}
    for amd in amendments:
        by_target.setdefault((amd.target, amd.target_suffix), []).append(amd)

    records = []
    audit.append(f"\n## 4. Amendments merged ({len(amendments)})\n")
    audit.append("Each was read off the rasterized Gazette pages. Partial replacements are\n"
                 "spliced against a quoted anchor of the original wording, and the splice\n"
                 "fails loudly rather than guessing if that quotation is missing or matches\n"
                 "more than once. Map: `law72_amendment_map.py`.\n")

    for art in articles:
        key = (art.number, None) if art.kind == "substantive" else None
        amds = by_target.pop(key, []) if key else []
        if amds:
            merged = apply_amendments(art.number, art.body, amds)
            body, amd_records = merged.text, merged.amendments
            for r in amd_records:
                audit.append(f"  article {art.number:>3}  {r['kind']:16s} "
                             f"{r['law_number']}/{r['law_year']}  {r['note']}")
        else:
            body, amd_records = art.body, []
        records.append((art, None, body, amd_records))

        # A مكرر article is inserted directly after its base-numbered sibling.
        bis = by_target.pop((art.number, "مكرر"), None) if key else None
        if bis:
            merged = apply_amendments(art.number, "", bis, suffix="مكرر")
            stub = Bis(art.number, "مكرر", art)
            records.append((stub, "مكرر", merged.text, merged.amendments))
            for r in merged.amendments:
                audit.append(f"  article {art.number:>3} مكرر  {r['kind']:16s} "
                             f"{r['law_number']}/{r['law_year']}  {r['note']}")

    if by_target:
        print(f"ERROR: unmatched amendment targets: {list(by_target)}", file=sys.stderr)
        return 1

    # 6. emit ---------------------------------------------------------------
    chunks = []
    for art, suffix, body, amd_records in records:
        header = build_header(art, suffix)
        display = f"{header}\n\n{body}"
        chunks.append({
            "chunk_id": chunk_id(art, suffix),
            "text_for_embedding": normalize_for_embedding(f"{header}\n{body}"),
            "text_for_display": display,
            "body_faithful": body,
            "header": header,
            "citation_label": build_citation(art, suffix),
            "metadata": {
                "law_name": LAW_NAME,
                "law_number": LAW_NUMBER,
                "law_year": LAW_YEAR,
                "jurisdiction": JURISDICTION,
                "issue_ref": None,
                "source_file": SOURCE_FILE,
                "article_type": art.kind,
                "article_number": art.number if art.kind == "substantive" else None,
                "article_suffix": suffix,
                "issuance_number": art.number if art.kind == "issuance" else None,
                "article_status": "active",
                "repealed_range": None,
                "division_number": None, "division_title": None,
                "book_number": None, "book_title": None,
                "part_number": art.book_number, "part_title": art.book_title,
                "part_kind": "normal",
                "chapter_number": art.chapter_number,
                "chapter_title": art.chapter_title,
                "section_number": None, "section_title": art.section_title,
                "subsection_title": None,
                "page_start": art.page_start, "page_end": art.page_end,
                "char_count": len(body),
                "approx_tokens": round(len(body) / CHARS_PER_TOKEN),
                "amendments": amd_records,
            },
        })

    out = SP / "chunks_law72.json"
    out.write_text(json.dumps(chunks, ensure_ascii=False, indent=2), encoding="utf-8")
    (SP / "law72_audit.md").write_text("\n".join(audit), encoding="utf-8")

    amended = sum(1 for c in chunks if c["metadata"]["amendments"])
    print(f"wrote {out.name}: {len(chunks)} chunks "
          f"({len(subs)} base articles + 2 مكرر + 10 issuance), "
          f"{amended} carry amendments")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
