"""Build chunks_law159.json: the Companies Law, as its consolidated edition reads.

Pipeline
--------
    extract + repair glyphs  ->  cut the explanatory memorandum
                             ->  parse articles  ->  emit chunks + audit

The output matches the schema `chunker.py` produces for laws 131 and 174, with
the two additions law 72 introduced:

    metadata.article_suffix   the full bis designation -- "مكرر", "مكرر ١",
                              "مكرر أ" -- or None. Not a flag: this law numbers
                              its bis articles in series (ten under 129, five
                              under 135), and each is a separate article with
                              its own text, so collapsing them would let the
                              citation guard verify an article it never saw.
    metadata.amendments       structured record of every amending law named
                              inside the article, so the corpus can be queried
                              by amendment as well as read.

Unlike law 72, no amendment merging happens here: this source is *already* a
consolidated annotated edition, so the superseded wording, the note naming the
amending law, and the replacement wording all arrive in one body. They stay
there (the system prompt's rule ٨ is what teaches the model to read them), and
the notes are additionally parsed into `metadata.amendments`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SP = Path(__file__).parent
sys.path.insert(0, str(SP))

from arabic_text import normalize_for_embedding  # noqa: E402
from law159_corrections import apply as apply_post_source_amendments  # noqa: E402
from law159_extract import extract_body  # noqa: E402
from law159_structure import (  # noqa: E402
    INT_TO_ORDINAL,
    ISSUANCE_ORDINALS,
    parse,
    to_arabic_digits,
)

LAW_NAME = "قانون الشركات"
LAW_NUMBER, LAW_YEAR = 159, 1981
SOURCE_FILE = "قانون الشركات رقم 159 لسنة 1981.pdf"
JURISDICTION = "مصر"
ISSUE_REF = "الجريدة الرسمية – العدد ٤٠ في أول أكتوبر ١٩٨١"
CHARS_PER_TOKEN = 1.8

# Sub-designations, for the ASCII half of a chunk_id only. The Arabic form is
# what every user-facing string uses.
_SUB_SLUG = {"أ": "a", "ب": "b", "ج": "c", "د": "d"}


def _suffix_slug(suffix: str | None) -> str:
    """"مكرر ١" -> "mukarrar-1"; "مكرر أ" -> "mukarrar-a"; "مكرر" -> "mukarrar"."""
    if not suffix:
        return ""
    sub = suffix.removeprefix("مكرر").strip()
    if not sub:
        return "mukarrar"
    slug = _SUB_SLUG.get(sub) or sub.translate(str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789"))
    return f"mukarrar-{slug}"


def _suffix_arabic(suffix: str | None) -> str:
    """"مكرر ١" -> ' مكررًا "١"'; "مكرر" -> " مكررًا"; None -> ""."""
    if not suffix:
        return ""
    sub = suffix.removeprefix("مكرر").strip()
    return f' مكررًا "{sub}"' if sub else " مكررًا"


def article_label(article) -> str:
    """«مادة (١٢٩ مكررًا "١")»."""
    return f"مادة ({to_arabic_digits(article.number)}{_suffix_arabic(article.suffix)})"


def build_header(article) -> str:
    lines = [
        f"{LAW_NAME} رقم ({to_arabic_digits(LAW_NUMBER)}) "
        f"لسنة ({to_arabic_digits(LAW_YEAR)})"
    ]
    if article.kind == "issuance":
        lines.append("من مواد الإصدار")
        lines.append(ISSUANCE_ORDINALS[article.number])
        return "\n".join(lines)
    if article.book_number:
        lines.append(f"الباب {INT_TO_ORDINAL[article.book_number]}: {article.book_title}")
    if article.chapter_number:
        lines.append(f"الفصل {INT_TO_ORDINAL[article.chapter_number]}: {article.chapter_title}")
    if article.section_title:
        lines.append(article.section_title)
    if article.subsection_title:
        lines.append(article.subsection_title)
    lines.append(article_label(article))
    return "\n".join(lines)


def build_citation(article) -> str:
    if article.kind == "issuance":
        return (
            f"{ISSUANCE_ORDINALS[article.number]} من مواد إصدار {LAW_NAME} "
            f"رقم {to_arabic_digits(LAW_NUMBER)} لسنة {to_arabic_digits(LAW_YEAR)}"
        )
    law = f"من {LAW_NAME} رقم {to_arabic_digits(LAW_NUMBER)} لسنة {to_arabic_digits(LAW_YEAR)}"
    number = f"{to_arabic_digits(article.number)}{_suffix_arabic(article.suffix)}"
    base = f"المادة ({number}) {law}"
    qualifier = article.chapter_title or article.book_title
    return f"{base} ({qualifier})" if qualifier else base


def chunk_id(article) -> str:
    base = f"{LAW_NUMBER}-{LAW_YEAR}"
    if article.kind == "issuance":
        return f"{base}-issuance-{article.number}"
    slug = _suffix_slug(article.suffix)
    return f"{base}-art-{article.number}-{slug}" if slug else f"{base}-art-{article.number}"


AUDIT_PREAMBLE = """# Law 159/1981 ingest -- record of every intervention

Generated by `build_law159.py`. Read this before ingesting: it lists everything
this pipeline changed relative to the source PDF, so each edit can be checked
against the source pages.

**What the source is.** A consolidated annotated edition of the Companies Law:
the enacted text with every amendment from 1994 to 2018 woven in, each marked
by a note naming the amending law and its Gazette reference. Those notes are
part of this edition and are kept verbatim in `body_faithful`; they are also
parsed into `metadata.amendments`.

**What was cut.** Pages 84-106 are a `مذكرة إيضاحية` -- the explanatory
memorandum to the draft bill. It is legislative history, not enacted text, and
quoting it as law would be wrong, so it never enters the corpus.

**What was NOT changed.** The two defects in section 3 are wrong in the source
itself. Repairing them would mean writing law, so they are reported instead of
guessed. Everything in section 2 is a font/extraction defect: the shapes drawn
on the page are correct Arabic, only the codepoints are wrong.

"""


def main() -> int:
    audit: list[str] = [AUDIT_PREAMBLE]

    pages, glyph_audit, memo_page = extract_body()
    audit.append("## 1. Scope\n")
    audit.append(f"  enacted text: pages 1-{len(pages)} "
                 f"(explanatory memorandum begins on page {memo_page}, dropped)")
    audit.append(f"  characters: {sum(len(p) for p in pages)}\n")

    audit.append("## 2. Glyph repairs\n")
    audit.append("Enumerated letter transpositions the font produces consistently:\n")
    for bad, good, count in glyph_audit["enumerated_fixes"]:
        audit.append(f"  {bad}  ->  {good}   (x{count})")
    unreviewed = glyph_audit["unreviewed_ar_tokens"]
    audit.append(
        "\nThe raa/zayn transposition (`الم ارفق` -> `المرافق`) was applied over the\n"
        "audited token universe in `law159_glyphs.py`. Tokens seen outside that\n"
        f"universe: {unreviewed or 'none'}.\n"
    )

    audit.append("## 3. Substantive defects left in place\n")
    audit.append("The source states something wrong here. Repairing it would mean\n"
                 "writing law, so it is surfaced instead of guessed.\n")
    for marker, note in glyph_audit["substantive_defects"]:
        audit.append(f"  {marker}\n      {note}")

    articles = parse(pages)
    substantive = [a for a in articles if a.kind == "substantive"]
    issuance = [a for a in articles if a.kind == "issuance"]

    numbers = {a.number for a in substantive if a.suffix is None}
    missing = [n for n in range(1, 185) if n not in numbers]
    keys = [a.key for a in substantive]
    if missing or len(set(keys)) != len(keys):
        print(f"ERROR: article numbering broken. missing={missing}", file=sys.stderr)
        return 1

    # Amendments enacted after the source edition was consolidated. Applied
    # after parsing, before anything reads status or bodies.
    applied = apply_post_source_amendments(articles)
    audit.append(f"\n## 3b. Amendments supplied by the project owner ({len(applied)})\n")
    audit.append("The source edition is consolidated to 2018, so a later amendment cannot\n"
                 "appear in it. These come from the project owner, are applied against an\n"
                 "anchor phrase, and fail the build rather than guess if that anchor moves.\n"
                 "Unlike the repeals the source itself marks, the pre-repeal wording is kept.\n")
    for article, amendment in applied:
        audit.append(f"  {article_label(article)}  repealed by قانون "
                     f"{to_arabic_digits(amendment.law_number)} لسنة "
                     f"{to_arabic_digits(amendment.law_year)}")
        audit.append(f"      note: {amendment.note}")

    bis = [a for a in substantive if a.suffix]
    repealed = [a for a in substantive if a.status == "repealed"]
    audit.append(f"\n## 4. Articles parsed ({len(articles)})\n")
    audit.append(f"  {len(issuance)} issuance + {len(substantive)} substantive "
                 f"({len(numbers)} base + {len(bis)} مكرر)")
    audit.append(f"  repealed (kept, marked article_status=\"repealed\"): "
                 f"{', '.join(article_label(a) for a in repealed)}\n")
    audit.append("### مكرر articles and their designations\n")
    for a in bis:
        audit.append(f"  {article_label(a):32} -> article_suffix={a.suffix!r}")

    amended = [a for a in substantive if a.amendments]
    by_law: dict[tuple[int, int], int] = {}
    for a in substantive:
        for record in a.amendments:
            key = (record["law_number"], record["law_year"])
            by_law[key] = by_law.get(key, 0) + 1
    audit.append(f"\n## 5. Amendments recorded ({sum(by_law.values())} notes "
                 f"across {len(amended)} articles)\n")
    audit.append("Parsed out of the notes the source itself carries; the notes stay\n"
                 "in body_faithful as well.\n")
    for (number, year), count in sorted(by_law.items(), key=lambda kv: -kv[1]):
        audit.append(f"  قانون {to_arabic_digits(number)} لسنة {to_arabic_digits(year)}"
                     f"   x{count}")

    chunks = []
    for article in articles:
        header = build_header(article)
        body = article.body
        chunks.append({
            "chunk_id": chunk_id(article),
            "text_for_embedding": normalize_for_embedding(f"{header}\n{body}"),
            "text_for_display": f"{header}\n\n{body}",
            "body_faithful": body,
            "header": header,
            "citation_label": build_citation(article),
            "metadata": {
                "law_name": LAW_NAME,
                "law_number": LAW_NUMBER,
                "law_year": LAW_YEAR,
                "jurisdiction": JURISDICTION,
                "issue_ref": ISSUE_REF,
                "source_file": SOURCE_FILE,
                "article_type": article.kind,
                "article_number": article.number if article.kind == "substantive" else None,
                "article_suffix": article.suffix,
                "issuance_number": article.number if article.kind == "issuance" else None,
                "article_status": article.status,
                "repealed_range": None,
                "division_number": None, "division_title": None,
                "book_number": None, "book_title": None,
                "part_number": article.book_number, "part_title": article.book_title,
                "part_kind": "normal",
                "chapter_number": article.chapter_number,
                "chapter_title": article.chapter_title,
                "section_number": None, "section_title": article.section_title,
                "subsection_title": article.subsection_title,
                "page_start": article.page_start, "page_end": article.page_end,
                "char_count": len(body),
                "approx_tokens": round(len(body) / CHARS_PER_TOKEN),
                "amendments": article.amendments,
            },
        })

    out = SP / "chunks_law159.json"
    out.write_text(json.dumps(chunks, ensure_ascii=False, indent=2), encoding="utf-8")
    (SP / "law159_audit.md").write_text("\n".join(audit), encoding="utf-8")

    print(f"wrote {out.name}: {len(chunks)} chunks "
          f"({len(numbers)} base articles + {len(bis)} مكرر + {len(issuance)} issuance), "
          f"{len(amended)} carry amendments, {len(repealed)} repealed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
