"""Text fixtures for the docgen parsers.

`masahma_namuzag.txt` is generated by `scripts/docgen_make_fixtures.py` from
the GAFI نموذج's PDF text layer. The other three are hand-written excerpts
reproducing the forms seen in the scanned samples, which have no text layer.
No test in this directory may touch the network or a database.
"""

from __future__ import annotations

import pathlib

import pytest

FIXTURES = pathlib.Path(__file__).resolve().parents[1] / "fixtures" / "docgen"


def _load(name: str) -> str:
    path = FIXTURES / name
    if not path.exists():
        pytest.skip(f"missing fixture {path}; run scripts/docgen_make_fixtures.py")
    return path.read_text(encoding="utf-8")


@pytest.fixture
def masahma_text() -> str:
    return _load("masahma_namuzag.txt")


@pytest.fixture
def zmm_text() -> str:
    return _load("zmm_injaz_excerpt.txt")


@pytest.fixture
def shakhs_wahed_text() -> str:
    return _load("shakhs_wahed_nour_excerpt.txt")


@pytest.fixture
def sijil_text() -> str:
    return _load("sijil_tijari_excerpt.txt")
